name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - uses: actions/checkout@v4
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Run ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check .

  validate:
    runs-on: ubuntu-latest
    name: HACS
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration
